2025-03-13 10:13:01 --- Archivo 2025-03-13 10.13.log creado con éxito en F:\Python\Proyecto Final Administradores de Bases de Datos\static\logs\2025-03-13 10.13.log
2025-03-13 10:13:01 ---  * Debugger is active!
2025-03-13 10:13:01 ---  * Debugger PIN: 827-411-152
2025-03-13 10:13:07 --- 127.0.0.1 - - [13/Mar/2025 10:13:07] "[33mGET /complete HTTP/1.1[0m" 404 -
2025-03-13 10:13:07 --- Se abrió la página Homepage desde: 127.0.0.1
2025-03-13 10:13:07 --- Se abrió la página Homepage desde: 127.0.0.1
2025-03-13 10:13:07 --- 127.0.0.1 - - [13/Mar/2025 10:13:07] "GET / HTTP/1.1" 200 -
2025-03-13 10:13:07 --- 127.0.0.1 - - [13/Mar/2025 10:13:07] "GET / HTTP/1.1" 200 -
2025-03-13 10:13:08 --- 127.0.0.1 - - [13/Mar/2025 10:13:08] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-03-13 10:13:12 --- 127.0.0.1 - - [13/Mar/2025 10:13:12] "GET /login/complete HTTP/1.1" 200 -
2025-03-13 10:13:12 --- 127.0.0.1 - - [13/Mar/2025 10:13:12] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-03-13 10:14:09 ---  * Detected change in 'F:\\Python\\Proyecto Final Administradores de Bases de Datos\\app.py', reloading
2025-03-13 10:14:09 --- Servidor desconectado
